"""
Event-driven architecture for Titan trading engine.

Defines immutable event classes using dataclasses with __slots__ for memory efficiency.
All events are hashable and JSON-serializable via orjson.
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Literal

__all__ = [
    "EventType",
    "TickEvent",
    "SignalEvent",
    "OrderRequestEvent",
    "RegimeEvent",
]


class EventType(str, Enum):
    """Enumeration of all event types in the trading engine."""

    TICK = "TICK"
    SIGNAL = "SIGNAL"
    ORDER_REQUEST = "ORDER_REQUEST"
    REGIME_TRENDING = "REGIME_TRENDING"
    REGIME_MEAN_REVERSION = "REGIME_MEAN_REVERSION"
    REGIME_RANGING = "REGIME_RANGING"


@dataclass(slots=True, frozen=True)
class TickEvent:
    """
    Market tick event representing a single price update.

    Attributes:
        symbol: Currency pair or instrument (e.g., 'EURUSD', 'XAUUSD').
        timestamp: UTC timestamp of the tick.
        bid: Current bid price (float).
        ask: Current ask price (float).
        volume: Volume in the tick (optional, defaults to 0.0).
    """

    symbol: str
    timestamp: datetime
    bid: float
    ask: float
    volume: float = 0.0

    @property
    def mid_price(self) -> float:
        """Calculate mid-price from bid/ask spread."""
        return (self.bid + self.ask) / 2.0

    @property
    def spread(self) -> float:
        """Calculate bid-ask spread in pips (for 5-decimal pairs)."""
        return (self.ask - self.bid) * 10000


@dataclass(slots=True, frozen=True)
class SignalEvent:
    """
    Trading signal generated by a strategy.

    Attributes:
        symbol: Currency pair or instrument.
        timestamp: When the signal was generated.
        direction: 'BUY', 'SELL', or 'NEUTRAL'.
        confidence: Confidence score [0.0, 1.0].
        regime: Current detected regime.
        price: Price at signal generation.
    """

    symbol: str
    timestamp: datetime
    direction: Literal["BUY", "SELL", "NEUTRAL"]
    confidence: float
    regime: str
    price: float

    def __post_init__(self) -> None:
        """Validate confidence is in [0.0, 1.0]."""
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be in [0.0, 1.0], got {self.confidence}")


@dataclass(slots=True, frozen=True)
class OrderRequestEvent:
    """
    Order execution request after risk validation.

    Attributes:
        symbol: Currency pair or instrument.
        timestamp: When the order was requested.
        direction: 'BUY' or 'SELL'.
        quantity: Number of units to trade.
        price: Limit price or market price indicator.
        risk_amount: Risk in account currency.
        signal_id: Reference to originating SignalEvent (for audit trail).
    """

    symbol: str
    timestamp: datetime
    direction: Literal["BUY", "SELL"]
    quantity: float
    price: float
    risk_amount: float
    signal_id: str  # hash or UUID of originating signal


@dataclass(slots=True, frozen=True)
class RegimeEvent:
    """
    Market regime detection event.

    Attributes:
        timestamp: When regime was detected.
        symbol: Currency pair.
        regime_type: Type of detected regime.
        r_squared: R² value for trend strength.
        z_score: Z-score for mean reversion magnitude.
    """

    timestamp: datetime
    symbol: str
    regime_type: Literal[
        "TRENDING", "MEAN_REVERSION", "RANGING"
    ]
    r_squared: float
    z_score: float
